Flowpack:
  Neos:
    DimensionResolver:
      contentDimensions:
        resolution:
          uriPathSegmentDelimiter: '_'

Neos:
  Flow:
    http:
      middlewares:
        'detectContentSubgraph':
          position: 'before routing'
          middleware: 'Flowpack\Neos\DimensionResolver\Http\DetectContentSubgraphMiddleware'
